server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
